services:
  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - VITE_APP_BACKEND_ADDRESS=https://localhost/api/prod
    container_name: frontend
    restart: always
    ports:
      - 5173:5173
  nodebackend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    volumes:
      - slack_db:/data/db
    image: mongo:latest
    ports:
      - '27017:27017'
volumes:
  slack_db:
